### ISSUE TITLE
implementation in voxel.js

### ISSUE THREAD

**Issue by ctzurcanu** [tunabrain/sparse-voxel-octrees#4]
Do you see any problem for this source to be ported to javascript? (Voxel.js benefits from webGL via three.js)
If no major problem, any advice on how someone could tackle this?

**Comment by tunabrain** [comment]
Doing it in JavaScript directly would probably be a challenge, since JS lacks support for certain bit twiddling hacks (such as reinterpreting int bits as an IEEE float and vice versa). It could probably be done if you removed some of the low-level optimizations and replaced them with JS friendlier versions. The lack of threading support and the slower nature of JS compared to C++ would definitely hurt you though, and I would expect slowdowns of a factor of 10-20, i.e. not real-time.

Since you mentioned WebGL, porting the raymarching part to GLSL and accelerating it using the GPU is definitely doable. I believe OpenGL ES 3.0 or 3.1 supports all the features you will need on the GLSL side (integer types and various bit twiddling functions).
If you wanted to go with this route, I would suggest building the Octree on the JS side using a direct port of the C++ code, followed by packing the data structure into integer textures for access on the GPU. The GLSL code could then be a more or less direct port of the C++ raymarching code; I think the only parts that would need changing are accesses to the data structure, since these would have to go through texture memory instead.

**Comment by ctzurcanu** [comment]
Thank you. This is a lot to absorb. Would you keep this issue with a label such as "idea for extension" or something similar? It may inspire me or other people to begin this re-implementation.

**Comment by tunabrain** [comment]
Closed due to inactivity.

**Comment by timbresmith** [comment]
I'm also interested in (and somewhat daunted by) the prospect of implementing SVOs or sparse voxel DAGs in webgl somehow.  There are some different examples of bits and pieces of this floating around.  If anyone wants to collaborate on this, let me know!
